port: 8080
mode: dev

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123"
  dbname: "test"
redis:
  addr: "localhost:6379"
  db: 0
  password:
log:
  level: 'info'
  filename: "run.log"
  max_size: 100
  max_age: 100
  max_backups: 100